name: Manually triggered release

run-name: Manual ${{ github.event.inputs.environment }} release of ${{ github.head_ref || github.ref_name }}

permissions:
  contents: "write"
  id-token: "write"

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to deploy'
        required: true
        default: 'f52ace8dcc'
        type: string

jobs:
  publish-release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: Setup build cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: 'Create Maven settings file'
        # https://github.com/whelk-io/maven-settings-xml-action
        # Oppretter default fil: ~/.m2/settings.xml
        uses: whelk-io/maven-settings-xml-action@v22
        with:
          repositories: '[
            { "id": "central", "url": "https://repo1.maven.org/maven2/", "releases": { "enabled": "true" }, "snapshots": { "enabled": "false" } },
            { "id": "github", "url": "https://maven.pkg.github.com/navikt/maven-release", "releases": { "enabled": "true" }, "snapshots": { "enabled": "true" } },
            { "id": "confluent", "url": "https://packages.confluent.io/maven/" }
          ]'
          servers: '[
            { "id": "github", "username": "x-access-token", "password": "${{ secrets.READER_TOKEN }}" },
            { "id": "github-dist", "username": "${{ github.actor }}", "password": "${{ github.token }}" }
          ]'

      - name: 'Perform release'
        run: |
          git config --local user.name 'GitHub Action[bot]'

          mvn -B -Dresume=false release:clean release:prepare release:perform
