name: Release (Github Package Registry)

run-name: Manual ${{ github.event.inputs.environment }} release of ${{ github.head_ref || github.ref_name }}


on:
  push:
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - "LICENCE"
      - "CODEOWNERS"
    branches:
      - 'main'

jobs:
  build-and-release:
    permissions:
      contents: "write"
      id-token: "write"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'maven'

      - name: 'Create Maven settings file'
        # https://github.com/whelk-io/maven-settings-xml-action
        # Oppretter default fil: ~/.m2/settings.xml
        uses: whelk-io/maven-settings-xml-action@v22
        with:
          repositories: '[
            { "id": "central", "url": "https://repo1.maven.org/maven2/", "releases": { "enabled": "true" }, "snapshots": { "enabled": "false" } },
            { "id": "github", "url": "https://maven.pkg.github.com/navikt/maven-release", "releases": { "enabled": "true" }, "snapshots": { "enabled": "true" } },
            { "id": "confluent", "url": "https://packages.confluent.io/maven/" }
          ]'
          servers: '[
            { "id": "github", "username": "x-access-token", "password": "${{ secrets.READER_TOKEN }}" },
            { "id": "github-dist", "username": "${{ github.actor }}", "password": "${{ github.token }}" }
          ]'

      - name: Run Maven release
        run: ./release.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
